[supabase]
url = "https://izaszyacumtrugtjtfcz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzQ2MjM2NzI2LCJleHAiOjIwNjE4MTI3MjZ9.I6ImFub24iLCJpYXQiOjE3NzIzMzQ2MTEsImV4cCI6MjA4NzM0NjEx0.8u-gGBDW99w5BRfH0lJNqb456knvxe047RiBZ_ifN6s"

APP_URL = "https://relatoriofinanceiro-ua9w8bfoe6ajqu6ynauset.streamlit.app"

[representantes]
"56abb99cda8bd7dd" = "Nome Representante|REGIAO 1;LOJAS"